services:

  db:
    image: postgres:16-alpine
    container_name: pms_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: AdminPassword123
      POSTGRES_DB: pms_db
    ports:
      
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d pms_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - pms_network

  backend:
    image: kaushalraj22/parking-management-system-backend:latest
    container_name: pms_backend
    restart: always
    environment:
      - DATABASE_URL=postgresql://postgres:AdminPassword123@db:5432/pms_db
      - SECRET_KEY=8f1c8413b5e43a6d91295b9c025daeeff0e9cb2b11e2f7b8c8d8a7a6b5c4d3e2
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=1440
      - PORT=5000
      - APP_ENV=production
      - COOKIE_SECURE=false # Set to true if running behind HTTPS/SSL
      - DEFAULT_ADMIN_USERNAME=admin
      - DEFAULT_ADMIN_PASSWORD=AdminPassword123
      - DEFAULT_ADMIN_EMAIL=admin@parkwise.com
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - pms_network

  frontend:
    image: kaushalraj22/parking-management-system-frontend:latest
    container_name: pms_frontend
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - pms_network

volumes:
  postgres_data:

networks:
  pms_network:
    driver: bridge
